name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: docker compose up -d --quiet-pull

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm i --ignore-scripts

      - run: npm t
